{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "b'{\"status\":\"ok\",\"totalResults\":140,\"articles\":[{\"source\":{\"id\":null,\"name\":\"Huffpost.com\"},\"author\":\"Daniel Marans\",\"title\":\"Joe Biden\\xe2\\x80\\x99s Absence Looms Over California Campaign Events\",\"description\":\"The former vice president\\'s rivals pounced on his controversial agenda at a San Francisco convention.\",\"url\":\"https://www.huffpost.com/entry/joe-biden-absence-looms-california-democrats_n_5cf33839e4b0e346ce7f59a4\",\"urlToImage\":\"https://img.huffingtonpost.com/asset/5cf339b92400005e07856733.jpeg?cache=zEgBgGSVIl&ops=1200_630\",\"publishedAt\":\"2019-06-02T03:26:27Z\",\"content\":\"SAN FRANCISCO \\xc2\\xa0No fewer than 14 Democratic presidential candidates were slated to speak at the California Democratic Party\\xe2\\x80\\x99s convention over the weekend. Eight of them did double duty at MoveOn.org\\xe2\\x80\\x99s Big Ideas forum a few blocks away. \\\\r\\\\nAnd a fifteenth conten\\xe2\\x80\\xa6 [+7511 chars]\"},{\"source\":{\"id\":null,\"name\":\"Cincinnati.com\"},\"author\":\"Cincinnati Enquirer, Cincinnati Enquirer\",\"title\":\"Joe Biden dubs Trump\\'s White House \\'bully pulpit\\', speaks out against anti-LGBTQ law\",\"description\":\"Democratic presidential candidate Joe Biden bashes Trump administration for setting a poor example on human rights.\",\"url\":\"https://www.cincinnati.com/story/news/politics/elections/2019/06/01/joe-biden-ohio-trumps-white-house-literally-bully-pulpit/1284117001?utm_source=google&utm_medium=amp&utm_campaign=speakable\",\"urlToImage\":\"https://www.gannett-cdn.com/presto/2019/06/02/PCIN/9a46ec56-936b-4399-b658-2f2272b8b4b0-0601_Biden.jpg?crop=1023,584,x0,y28&width=3200&height=1680&fit=bounds\",\"publishedAt\":\"2019-06-02T20:03:20Z\",\"content\":\"Democratic presidential candidate, former Vice President Joe Biden speaks during the Human Rights Campaign dinner at Ohio State University, Saturday, June 1, 2019, in Columbus, Ohio. (AP Photo/Paul Vernon)\\\\r\\\\n\\xc2\\xa0(Photo: Paul Vernon, AP)\\\\r\\\\nCOLUMBUS, Ohio - Democrat\\xe2\\x80\\xa6 [+3581 chars]\"},{\"source\":{\"id\":\"usa-today\",\"name\":\"USA Today\"},\"author\":\"USA TODAY, Aamer Madhani, USA TODAY\",\"title\":\"Biden faces stiff criticism from Democrats for skipping California convention\",\"description\":\"Joe Biden was the only top tier White House hopeful to take a pass on the convention that draws some of state\\'s most active Democrat supporters.\",\"url\":\"https://www.usatoday.com/story/news/politics/elections/2019/06/02/joe-biden-criticized-by-california-democrats-for-skipping-convention/1289268001/?utm_source=google&utm_medium=amp&utm_campaign=speakable\",\"urlToImage\":\"https://www.gannett-cdn.com/presto/2019/06/02/USAT/de699c99-30e0-44a8-823e-063337341928-Joe_Biden_California_no_show.JPG?crop=3753,2097,x0,y48&width=3200&height=1680&fit=bounds\",\"publishedAt\":\"2019-06-02T13:38:54Z\",\"content\":\"Bernie Sanders and Kamala Harris dueled Friday over Hispanic votes in California, a central front in the nation\\'s immigration battle where Latinos represent the state\\'s largest ethnic group. (May 31)\\\\r\\\\n AP, AP\\\\r\\\\nSAN FRANCISCO Democratic presidential frontrunner\\xe2\\x80\\xa6 [+7929 chars]\"},{\"source\":{\"id\":null,\"name\":\"Vox.com\"},\"author\":\"Gabriela Resto-Montero\",\"title\":\"Democratic presidential candidates call for change at California\\xe2\\x80\\x99s Democratic Party Convention\",\"description\":\"14 presidential candidates spoke at the convention, and all but one called for a break from the past.\",\"url\":\"https://www.vox.com/policy-and-politics/2019/6/2/18649361/2020-democratic-presidential-candidates-california-democratic-party-convention\",\"urlToImage\":\"https://cdn.vox-cdn.com/thumbor/SQXiy2Wl3cMv0Y0mcpYc_acpsl0=/0x0:5000x2618/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/16314609/GettyImages_1153164233.jpg\",\"publishedAt\":\"2019-06-02T15:37:32Z\",\"content\":\"14 presidential candidates spoke at the convention, and all but one called for a break from the past. Democratic presidential hopefuls pitched themselves to primary voters in San Francisco, California Saturday with calls for the party to embrace big changes. \\xe2\\x80\\xa6 [+7071 chars]\"},{\"source\":{\"id\":\"politico\",\"name\":\"Politico\"},\"author\":\"Carla Marinucci\",\"title\":\"\\'I\\'m not a Bernie Bro\\': Sanders\\' base splinters in California\",\"description\":\"Other progressive candidates and a home state-senator are showing why Sanders may have a tough time winning in this liberal-leaning, delegate-rich state.\",\"url\":\"https://www.politico.com/story/2019/06/02/bernie-sanders-moveon-california-1349552\",\"urlToImage\":\"https://static.politico.com/98/cf/8e66140942c3b1160ab9fc5f3940/1961-bernie-sanders-gty-773.jpg\",\"publishedAt\":\"2019-06-02T11:06:43Z\",\"content\":\"Sen. Bernie Sanders greets the crowd at the MoveOn Big Ideas Forum at The Warfield Theatre on Saturday in San Francisco. | Kimberly White/Getty Images for MoveOn\\\\r\\\\nSAN FRANCISCO Bernie Sanders put down roots in California during the last presidential race and \\xe2\\x80\\xa6 [+8831 chars]\"},{\"source\":{\"id\":\"politico\",\"name\":\"Politico\"},\"author\":\"Carla Marinucci\",\"title\":\"Harris challenges Axelrod over criticism she\\'s too \\'cautious\\' on trail\",\"description\":\"Sen. Kamala Harris on Saturday pushed back at the emerging narrative that she\\xe2\\x80\\x99s been too timid while campaigning for president.\",\"url\":\"https://www.politico.com/story/2019/06/01/kamala-harris-david-axelrod-2020-campaign-1349600\",\"urlToImage\":\"https://static.politico.com/29/fd/328cf0ad45028ece0917735e0091/060119-kamala-harris-ap-773.jpg\",\"publishedAt\":\"2019-06-02T00:22:12Z\",\"content\":\"Democratic presidential candidate Sen. Kamala Harris gestures in front of Rep. Barbara Lee before speaking during the 2019 California Democratic Party State Organizing Convention in San Francisco, Saturday, June 1, 2019. | AP Photo/Jeff Chiu\\\\r\\\\nSAN FRANCISCO Se\\xe2\\x80\\xa6 [+3356 chars]\"},{\"source\":{\"id\":null,\"name\":\"Theintercept.com\"},\"author\":\"Liliana Segura\",\"title\":\"Henry Montgomery Paved the Way for Other Juvenile Lifers to Go Free. Now 72, He May Never Get the Same Chance.\",\"description\":\"\\xe2\\x80\\x9cIt obviously didn\\xe2\\x80\\x99t register with him what had happened,\\xe2\\x80\\x9d said one attendee at Montgomery\\xe2\\x80\\x99s parole hearing. \\xe2\\x80\\x9cHe just looked stunned. As we all did.\\xe2\\x80\\x9d The post Henry Montgomery Paved the Way for Other Juvenile Lifers to Go Free. Now 72, He May Never Get the Sa\\xe2\\x80\\xa6\",\"url\":\"https://theintercept.com/2019/06/02/henry-montgomery-juvenile-life-without-parole/\",\"urlToImage\":\"https://theintercept.imgix.net/wp-uploads/sites/1/2019/05/henry-montgomery-advocate-1559079168-e1559079684677.jpg?auto=compress%2Cformat&q=90&fit=crop&w=1200&h=800\",\"publishedAt\":\"2019-06-02T12:00:42Z\",\"content\":\"As Eric Alexander\\\\r\\\\n entered the Louisiana State Penitentiary, known as Angola, he found himself transported back 25 years, to a place he had never wished to revisit. All these things that I observed upon walking into prison for the first time as a teenager, I\\xe2\\x80\\xa6 [+18478 chars]\"},{\"source\":{\"id\":null,\"name\":\"Theintercept.com\"},\"author\":\"Intercepted\",\"title\":\"\\xe2\\x80\\x9cWe\\xe2\\x80\\x99ve Got People:\\xe2\\x80\\x9d Ryan Grim on the Democratic Party, Nancy Pelosi, and 2020 Campaign\",\"description\":\"In this bonus episode, The Intercept\\xe2\\x80\\x99s Ryan Grim joins for an extended conversation about his new book, \\\\\"We\\'ve Got People.\\\\\" The post \\xe2\\x80\\x9cWe\\xe2\\x80\\x99ve Got People:\\xe2\\x80\\x9d Ryan Grim on the Democratic Party, Nancy Pelosi, and 2020 Campaign appeared first on The Intercept.\",\"url\":\"https://theintercept.com/2019/06/02/ryan-grim-book-democratic-party/\",\"urlToImage\":\"https://theintercept.imgix.net/wp-uploads/sites/1/2019/05/weve-got-people-bonus-episode-1559331877.jpg?auto=compress%2Cformat&q=90&fit=crop&w=1200&h=800\",\"publishedAt\":\"2019-06-02T10:01:29Z\",\"content\":\"As Democrats continue\\\\r\\\\n to debate whether to initiate an impeachment inquiry, Trump seems to be going nuts from the Democrats continuing probe into his possible obstruction of justice, corruption, abuse of power. The Intercepts Ryan Grim explains Nancy Pelosi\\xe2\\x80\\xa6 [+57658 chars]\"},{\"source\":{\"id\":null,\"name\":\"Deadline.com\"},\"author\":\"Anita Bennett\",\"title\":\"Kamala Harris Appearance Interrupted By Protester Who Grabbed Her Microphone\",\"description\":\"A presidential candidates forum at the 2019 California Democratic Party State Convention turned chaotic Saturday, when a protester stormed the stage during an appearance by Sen. Kamala Harris (D-California). Harris was seated on stage at MoveOn\\xe2\\x80\\x99s \\xe2\\x80\\x9cBig Ideas\\xe2\\x80\\x9d \\xe2\\x80\\xa6\",\"url\":\"https://deadline.com/2019/06/kamala-harris-appearance-interrupted-by-protester-who-grabbed-her-microphone-1202625583/\",\"urlToImage\":\"https://pmcdeadline2.files.wordpress.com/2019/06/10266109q.jpg?w=1024\",\"publishedAt\":\"2019-06-02T00:20:59Z\",\"content\":\"A presidential candidates forum at the 2019 California Democratic Party State Convention turned chaotic Saturday, when a protester stormed the stage during an appearance by Sen. Kamala Harris (D-California).\\\\r\\\\nHarris was seated on stage at MoveOn\\xe2\\x80\\x99s \\xe2\\x80\\x9cBig Ideas\\xe2\\x80\\x9d\\xe2\\x80\\xa6 [+1804 chars]\"},{\"source\":{\"id\":null,\"name\":\"Forbes.com\"},\"author\":\"Ken Silverstein, Contributor, Ken Silverstein, Contributor https://www.forbes.com/sites/kensilverstein/\",\"title\":\"The Pursuit Of Carbon Capture Is A More Rational Policy Than The Rejection Of Climate Science\",\"description\":\"Renewables are projected escalate while fossil fuels will remain staples of the global economy. The United States must pursue low-carbon policies while continuing to research and develop carbon capture technologies \\xe2\\x80\\x94 a more practical approach to energy policy\\xe2\\x80\\xa6\",\"url\":\"https://www.forbes.com/sites/kensilverstein/2019/06/02/the-pursuit-of-carbon-capture-is-a-more-rational-policy-than-the-rejection-of-climate-science/\",\"urlToImage\":\"https://thumbor.forbes.com/thumbor/600x315/https%3A%2F%2Fspecials-images.forbesimg.com%2Fdam%2Fimageserve%2F97e4f52efb7c459ead8c17bb2787c7d3%2F960x0.jpg%3Ffit%3Dscale\",\"publishedAt\":\"2019-06-02T16:02:00Z\",\"content\":\"Share to facebook\\\\r\\\\nShare to twitter\\\\r\\\\nShare to linkedin\\\\r\\\\nClimate change activists holding signs join in on a rally supporting the &amp;quot;Green New Deal&amp;quot; in Pershing Square in downtown Los Angeles on Friday, May 24, 2019. (AP Photo/Richard Vogel)\\\\r\\\\nA\\xe2\\x80\\xa6 [+11914 chars]\"},{\"source\":{\"id\":null,\"name\":\"Washingtonexaminer.com\"},\"author\":\"\",\"title\":\"Is Trump making the Democrats moderate again? - Washington Examiner\",\"description\":\"Is Trump making the Democrats moderate again? Washington Examiner Biden: Fastest way to end transgender violence \\'is to end the Trump administration\\' CNN Can Joe Biden be both the future and the past? The Washington Post Joe Biden tells Ohio crowd that an LGB\\xe2\\x80\\xa6\",\"url\":\"https://www.washingtonexaminer.com/opinion/op-eds/is-trump-making-the-democrats-moderate-again\",\"urlToImage\":\"https://mediadc.brightspotcdn.com/dims4/default/a3dd771/2147483647/strip/true/crop/2290x1202+0+60/resize/1200x630!/quality/90/?url=https%3A%2F%2Fmediadc.brightspotcdn.com%2F8f%2Fe3%2F4c3abcce478d89361d8864313819%2Fap-19082010950880.jpg\",\"publishedAt\":\"2019-06-02T04:00:00Z\",\"content\":\"Pundits have long believed that public disdain for the Trump presidency would usher in an equally radical leftist to the Oval Office. Thomas Edsall, of the New York Times, has suggested that since Trump threw out conventional wisdom, Democrats may be in the p\\xe2\\x80\\xa6 [+4366 chars]\"},{\"source\":{\"id\":\"abc-news\",\"name\":\"ABC News\"},\"author\":\"Christopher Donato\",\"title\":\"Joe Biden calls Trump administration \\'disaster for human rights\\' at LGBT event - ABC News\",\"description\":\"Joe Biden calls Trump administration \\'disaster for human rights\\' at LGBT event ABC News Former Vice President Joe Biden spoke to about 750 people at the annual Human Rights Campaign Columbus Dinner in Ohio Saturday night where he went... View full coverage on\\xe2\\x80\\xa6\",\"url\":\"https://abcnews.go.com/Politics/joe-biden-calls-trump-administration-disaster-human-rights/story?id=63428999\",\"urlToImage\":\"https://s.abcnews.com/images/Politics/biden-human-rights2-ap-mo-20190602_hpMain_16x9_992.jpg\",\"publishedAt\":\"2019-06-02T04:34:00Z\",\"content\":\"Former Vice President Joe Biden spoke to about 750 people at the annual Human Rights Campaign Columbus Dinner in Ohio Saturday night where he went after the Trump administration for being a \\\\\"disaster for human rights\\\\\" on the first day of LGBT Pride Month.\\\\r\\\\nIn\\xe2\\x80\\xa6 [+3515 chars]\"},{\"source\":{\"id\":null,\"name\":\"Sltrib.com\"},\"author\":\"https://www.facebook.com/saltlaketribune\",\"title\":\"George F. Will: The idea of an aesthetic impeachment - Salt Lake Tribune\",\"description\":\"George F. Will: The idea of an aesthetic impeachment Salt Lake Tribune Democrats, in California, confront deep divisions over how to handle increasing calls for President Trump\\xe2\\x80\\x99s impeachment The Washington Post Pelosi promises \\'ironclad case\\' against Trump | \\xe2\\x80\\xa6\",\"url\":\"https://www.sltrib.com/opinion/commentary/2019/06/02/george-f-will-idea-an/\",\"urlToImage\":\"https://www.sltrib.com/resizer/2lC-2qkeFssK7nLnW2IEgjekelA=/1200x630/filters:quality(85)/arc-anglerfish-arc2-prod-sltrib.s3.amazonaws.com/public/YMT2DC27T5FATHLYNDYRNUWHAM.jpg\",\"publishedAt\":\"2019-06-02T00:03:59Z\",\"content\":\"Washington If congressional Democrats will temper their enthusiasm for impeachment with lucidity about the nations needs and their political self-interest, they will understand the self-defeating nature of a foredoomed attempt to remove a president for aesthe\\xe2\\x80\\xa6 [+5197 chars]\"},{\"source\":{\"id\":\"business-insider\",\"name\":\"Business Insider\"},\"author\":\"Associated Press\",\"title\":\"Joe Biden says LGBTQ rights will be his top legislative priority - Business Insider\",\"description\":\"Joe Biden says LGBTQ rights will be his top legislative priority Business Insider Biden spoke Saturday about LGBTQ rights at a keynote address to hundreds of activists at the Human Rights Campaign\\'s annual Ohio gala.\",\"url\":\"https://www.businessinsider.com/joe-biden-lgbtq-rights-top-legislative-priority-2019-6\",\"urlToImage\":\"https://amp.businessinsider.com/images/5cf32afd11e2051646254b52-1536-768.jpg\",\"publishedAt\":\"2019-06-02T02:05:47Z\",\"content\":\"COLUMBUS, Ohio (AP) \\xe2\\x80\\x94 Democratic presidential candidate Joe Biden declared Saturday that the Equality Act would be his top legislative priority, an effort to enshrine LGBTQ protections into the nation\\'s labor and civil rights laws. \\\\r\\\\n The former vice presiden\\xe2\\x80\\xa6 [+6177 chars]\"},{\"source\":{\"id\":\"business-insider\",\"name\":\"Business Insider\"},\"author\":\"Associated Press\",\"title\":\"Leading Democratic candidates took subtle digs at Joe Biden while he was absent at an event that most of them attended - Business Insider\",\"description\":\"Leading Democratic candidates took subtle digs at Joe Biden while he was absent at an event that most of them attended Business Insider Fourteen presidential contenders attended a three-day gathering in California, featuring thousands of activists. Biden was \\xe2\\x80\\xa6\",\"url\":\"https://www.businessinsider.com/democratic-candidates-take-subtle-digs-at-biden-2019-6\",\"urlToImage\":\"https://amp.businessinsider.com/images/5cf3344f11e2050f7a13ccb3-1920-960.jpg\",\"publishedAt\":\"2019-06-02T02:39:21Z\",\"content\":\"SAN FRANCISCO (AP) \\xe2\\x80\\x94 Democratic presidential hopefuls took rival Joe Biden\\'s absence at a California state party gathering Saturday as a chance to take subtle digs at the former vice president and craft themselves as better positioned to bring Democrats into \\xe2\\x80\\xa6 [+6317 chars]\"},{\"source\":{\"id\":null,\"name\":\"Wtop.com\"},\"author\":\"The Associated Press\",\"title\":\"Update on the latest news, sports, business and entertainment at 12:20 a.m. EDT - WTOP\",\"description\":\"Update on the latest news, sports, business and entertainment at 12:20 a.m. EDT WTOP AP-US-VIRGINIA-BEACH-SHOOTING-THE-LATEST The Latest: Note says shooter\\xe2\\x80\\x99s family sends condolences VIRGINIA BEACH, Va. (AP) \\xe2\\x80\\x94 A handwritten note at the home of the Virginia Be\\xe2\\x80\\xa6\",\"url\":\"http://wtop.com/national/2019/06/update-on-the-latest-news-sports-business-and-entertainment-at-1220-a-m-edt-160/\",\"urlToImage\":\"https://wtop.com/wp-content/uploads/2017/04/wtop_logo_512x512.png\",\"publishedAt\":\"2019-06-02T04:00:00Z\",\"content\":\"A NATION OF TRAUMA\\\\r\\\\nMass shootings create rippling network of stricken survivors\\\\r\\\\nCHICAGO (AP) The litany of mass shootings in recent years has changed how America talks, prays and prepares for trouble.\\\\r\\\\nToday, the phrases \\xe2\\x80\\x9cactive shooter\\xe2\\x80\\x9d and \\xe2\\x80\\x9cshelter in pla\\xe2\\x80\\xa6 [+9089 chars]\"},{\"source\":{\"id\":\"spiegel-online\",\"name\":\"Spiegel Online\"},\"author\":\"SPIEGEL ONLINE\",\"title\":\"Pr\\xc3\\xa4sidentschaftsbewerber in den USA: Joe Biden will sich f\\xc3\\xbcr Homo- und Transsexuelle einsetzen\",\"description\":\"Joe Biden sichert Schwulen, Lesben, Bisexuellen und Transgender seine Unterst\\xc3\\xbctzung zu, falls er n\\xc3\\xa4chster US-Pr\\xc3\\xa4sident werden sollte. Kurz zuvor hatte Amtsinhaber Donald Trump angek\\xc3\\xbcndigt, sich f\\xc3\\xbcr Homosexuelle stark zu machen.\",\"url\":\"https://www.spiegel.de/politik/ausland/joe-biden-erklaert-rechte-von-homo-und-transsexuellen-zur-prioritaet-a-1270425.html\",\"urlToImage\":\"https://cdn1.spiegel.de/images/image-1434385-860_poster_16x9-yskj-1434385.jpg\",\"publishedAt\":\"2019-06-02T13:07:11Z\",\"content\":\"Sonntag, 02.06.2019 \\xc2\\xa0\\\\r\\\\n15:07 Uhr\\\\r\\\\nIm Juni feiern Schwule, Lesben, Bisexuelle und Transgender (LGBT) in den USA den sogenannten Pride Month. Sie zelebrieren den offenen Umgang mit ihrer sexuellen Identit\\xc3\\xa4t und werben f\\xc3\\xbcr mehr Toleranz.\\\\r\\\\nP\\xc3\\xbcnktlich zum Start des\\xe2\\x80\\xa6 [+1965 chars]\"},{\"source\":{\"id\":null,\"name\":\"Americanthinker.com\"},\"author\":null,\"title\":\"Can Our Nation Conduct an Honest Election in 2020?\",\"description\":\"Given the Democrats\\' alarming record of public misconduct, what can we expect from them in the run-up to the next presidential election?\",\"url\":\"https://www.americanthinker.com/articles/2019/06/can_our_nation_conduct_an_honest_election_in_2020.html\",\"urlToImage\":\"https://www.americanthinker.com/images/bucket/2019-05/213560.jpg\",\"publishedAt\":\"2019-06-02T05:00:00Z\",\"content\":\"As you watch the rally live, you realize that the majority of Americans have never had the opportunity to witness Trump\\'s ability to connect in such a genuine fashion with his audience and supporters.\\xc2\\xa0\\xc2\\xa0He wins loyal support by promoting a set of policies that\\xe2\\x80\\xa6 [+13069 chars]\"},{\"source\":{\"id\":null,\"name\":\"Infowars.com\"},\"author\":\"Steve Watson\",\"title\":\"Democrats Politicize Virginia Beach Shooting To Push Gun Control, Second Amendment Supporters Push Back\",\"description\":\"All Democrats needed was news of a mass shooting to echo their calls for gun control.\",\"url\":\"https://www.infowars.com/democrats-politicize-virginia-beach-shooting-to-push-gun-control-second-amendment-supporters-push-back/\",\"urlToImage\":\"https://assets.infowars.com/2018/03/3-22-18-gun.jpg\",\"publishedAt\":\"2019-06-02T11:24:15Z\",\"content\":\"Many Democrats, including most 2020 presidential candidates, were quick to politicize the tragic mass shooting in Virginia Beach to push their gun control agenda, but Second Amendment supporters weren\\xe2\\x80\\x99t about to take any of it lying down.\\\\r\\\\nNews broke Friday t\\xe2\\x80\\xa6 [+1728 chars]\"},{\"source\":{\"id\":null,\"name\":\"Goodmenproject.com\"},\"author\":\"Tim Clark\",\"title\":\"Bill de Blasio, He Might Surprise You\",\"description\":\"Left of Center, and Under the Radar. The post Bill de Blasio, He Might Surprise You appeared first on The Good Men Project.\",\"url\":\"https://goodmenproject.com/featured-content/bill-de-blasio-he-might-surprise-you-kpkn/\",\"urlToImage\":\"https://goodmenproject.com/wp-content/uploads/2019/05/Bill_de_Blasio.gmp_.jpg\",\"publishedAt\":\"2019-06-02T17:30:07Z\",\"content\":\"Bill di Blasio is a complicated guy. A complicated guy to write about anyway. Mostly because he is so new to the crowded, confusing field of candidates I had to research everything. Research takes time, even now. What I found was impressive. He has some real \\xe2\\x80\\xa6 [+4190 chars]\"}]}'\n"
     ]
    }
   ],
   "source": [
    "import urllib\n",
    "\n",
    "url = ('https://newsapi.org/v2/everything?'\n",
    "       'q=Biden&'\n",
    "       'from=2019-06-02&'\n",
    "       'sortBy=popularity&'\n",
    "       'apiKey=63218b4ea1cf42b896ddccf80961b5d8')\n",
    "\n",
    "response = urllib.request.urlopen(url)\n",
    "\n",
    "\n",
    "print(response.read())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(['https://www.cnn.com/2018/12/31/politics/trump-syria-four-months-nyt/index.html?utm_source=feedburner&amp;utm_medium=feed&amp;utm_campaign=Feed%3A+rss%2Fcnn_allpolitics+%28RSS%3A+CNN+-+Politics%29',\n",
       "  'https://www.govexec.com/contracting/2018/12/government-may-be-shut-down-taxpayers-are-footing-bill-mar-lago-party-tents/153789/?oref=ge-android-article-share',\n",
       "  'https://abcnews.go.com/Politics/wireStory/latest-trump-hed-love-run-warren-60097478',\n",
       "  'https://www.nytimes.com/2018/03/04/world/europe/state-department-russia-global-engagement-center.html?fbclid=IwAR1Kn_jFKNhs4ji77JZUG2jJmSCoYx0yeInGjMMl9Mpc4RvMHUIe74zPGGA',\n",
       "  'https://www.inquisitr.com/5228425/taxpayers-pick-up-54k-bill-for-tents-at-trumps-swanky-new-years-party-at-mar-a-lago-that-he-wont-attend/'],\n",
       " 131279)"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data[0:5], len(data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "0dbe91749b5b4316a07de8ef4e420ac6",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, max=131279), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/Cellar/ipython/7.4.0/libexec/vendor/lib/python3.7/site-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname CST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  category=UnknownTimezoneWarning)\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "/usr/local/Cellar/ipython/7.4.0/libexec/vendor/lib/python3.7/site-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname PST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  category=UnknownTimezoneWarning)\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "/usr/local/Cellar/ipython/7.4.0/libexec/vendor/lib/python3.7/site-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname CDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  category=UnknownTimezoneWarning)\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: utf-8 data-n-head=true\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Building prefix dict from /usr/local/lib/python3.7/site-packages/jieba/dict.txt ...\n",
      "Dumping model to file cache /var/folders/wg/klpk39_51vl771cjtbb6p0jr0000gn/T/jieba.cache\n",
      "Loading model cost 1.3837580680847168 seconds.\n",
      "Prefix dict has been built succesfully.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: utf-8 data-n-head=true\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: utf-8, ie=edge, chrome=1\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: utf-8 data-n-head=true\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "/usr/local/Cellar/ipython/7.4.0/libexec/vendor/lib/python3.7/site-packages/dateutil/parser/_parser.py:1206: UnknownTimezoneWarning: tzname HST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.\n",
      "  category=UnknownTimezoneWarning)\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n",
      "error getting summary: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 189, in summary\n",
      "    self._html(True)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 132, in _html\n",
      "    self.html = self._parse(self.input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/readability.py\", line 141, in _parse\n",
      "    doc, self.encoding = build_doc(input)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/htmls.py\", line 17, in build_doc\n",
      "    encoding = get_encoding(page) or 'utf-8'\n",
      "  File \"/usr/local/lib/python3.7/site-packages/readability/encoding.py\", line 46, in get_encoding\n",
      "    page.decode(encoding)\n",
      "LookupError: unknown encoding: ><script type=\n"
     ]
    }
   ],
   "source": [
    "import zipfile\n",
    "from newsplease import NewsPlease\n",
    "from tqdm import tqdm_notebook as tqdm\n",
    "\n",
    "with zipfile.ZipFile('articlelinks.zip', 'r').open(\"articlelinks.txt\", \"r\") as f:\n",
    "    data = eval(f.readline())\n",
    "    \n",
    "missed_rows = []\n",
    "try:\n",
    "    with open(\"article_data.csv\", 'w') as f:\n",
    "        for i in tqdm(range(len(data))):\n",
    "            try:\n",
    "                news = NewsPlease.from_url(data[i], timeout=5)\n",
    "                f.write(\"{}, {} \\n\".format(data[i], news.get_serializable_dict()))\n",
    "            except Exception as e:\n",
    "                missed_rows.append((i, data[i]))\n",
    "except Exception as f:\n",
    "    print(missed_rows)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
